### ISSUE TITLE
grunt Warning: Task "test" not found. Use --force to continue.  Aborted due to warnings.

### ISSUE THREAD

**Issue by spoetnik** [DrupalHub/drupalhub#205]
Running Grunt in the design folder stops with an error:

    grunt
    Warning: Task "test" not found. Use --force to continue.

    Aborted due to warnings.

If I comment out the 'test' in this line, all is working good:
https://github.com/DrupalHub/drupalhub/blob/master/design/Gruntfile.js#L477

**Comment by RoySegall** [comment]
I'm having some issues today with npm, grunt and drush make. Any other errors?

**Comment by spoetnik** [comment]
During install yes, a few times for missing Ruby-dev, npm-legacy etc, but after a succesfull clean install, no other issues. 

My debug console complains about a missing  css, but I relate this to the Grunt error.

**Comment by RoySegall** [comment]
Try to do a `npm cache clean`, clone a fresh copy of the project and run the script again.

**Comment by RoySegall** [comment]
I think I got it. The packeges in the bower are wrong. I'm cehcking.

**Comment by spoetnik** [comment]
sorry, yes, another error. Is this related?
vagrant@vagrantbox:/vagrant/www/design$ node app/js/Nodejs/socket.js

module.js:340
    throw err;
          ^
    Error: Cannot find module '/vagrant/www/design/app/js/Nodejs/socket.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:902:3

**Comment by RoySegall** [comment]
the error above should not occure since we no longer use a Socket js. That's weird. Any way, i think we have something else then version of the bower components since the travis has passed. I'll look for answer in the bower community.

**Comment by spoetnik** [comment]
The above error is from this line in the install script:
https://github.com/DrupalHub/drupalhub/blob/master/default.install.sh#L43

**Comment by RoySegall** [comment]
Oops... I was pretty sure i removed it. Should be deleted.

**Comment by RoySegall** [comment]
Boom! got it. try `sudo npm install -g bower@1.4`

**Comment by spoetnik** [comment]
Sweet that fixed it!
